// This script runs on Railway during deployment.
// It reads your secret keys from Railway's environment variables
// and writes them into config.js so the app can use them.
// This file is safe to commit — it contains no secrets, only variable names.

const fs = require('fs');

const config = `// ⚙️ Auto-generated by Railway — do not edit manually.
var FIREBASE_CONFIG = {
  apiKey:            '${process.env.FIREBASE_API_KEY || ''}',
  authDomain:        '${process.env.FIREBASE_AUTH_DOMAIN || ''}',
  projectId:         '${process.env.FIREBASE_PROJECT_ID || ''}',
  storageBucket:     '${process.env.FIREBASE_STORAGE_BUCKET || ''}',
  messagingSenderId: '${process.env.FIREBASE_MESSAGING_SENDER_ID || ''}',
  appId:             '${process.env.FIREBASE_APP_ID || ''}'
};

const EMAILJS_SERVICE_ID  = '${process.env.EMAILJS_SERVICE_ID || ''}';
const EMAILJS_TEMPLATE_ID = '${process.env.EMAILJS_TEMPLATE_ID || ''}';
const EMAILJS_PUBLIC_KEY  = '${process.env.EMAILJS_PUBLIC_KEY || ''}';
`;

fs.writeFileSync('config.js', config);
console.log('✅ config.js generated successfully from environment variables.');
